CREATE USER IF NOT EXISTS `$MARIADB_USER`@`%` identified by '$MARIADB_ROOT_PASSWORD';

CREATE DATABASE IF NOT EXISTS `empresa`;
CREATE DATABASE IF NOT EXISTS `hospital`;
CREATE DATABASE IF NOT EXISTS `jardineria`;
CREATE DATABASE IF NOT EXISTS `modelsclassics`;

GRANT ALL PRIVILEGES ON `empresa`.* TO `$MARIADB_USER`@`%`;
GRANT ALL PRIVILEGES ON `hospital`.* TO `$MARIADB_USER`@`%`;
GRANT ALL PRIVILEGES ON `jardineria`.* TO `$MARIADB_USER`@`%`;
GRANT ALL PRIVILEGES ON `modelsclassics`.* TO `$MARIADB_USER`@`%`;

FLUSH PRIVILEGES;
